export const SET_LOGIN='SET_LOGIN'
export const SET_SIGNUP='SET_SIGNUP'
export const CREATE_USER = "CREATE_USER";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_GAME = "CREATE_GAME";
export const GET_CATEGORIES = "GET_CATEGORIES";
